import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.project.deleteMany()

  const projects = [
    // ─── ONGOING / CURRENT ───────────────────────────────────────────────────
    {
      title: 'Marle Pit Hill Bridge Reconstruction',
      reference: 'SPC5-94',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'As part of the Midland Main Line Electrification scheme, I am working as the designer for the reconstruction of a two-span masonry arch to allow for adequate gauging clearance. The proposed construction is a continuous integral joist in concrete deck with sandwich parapets.',
      role: 'Design Engineer',
      latitude: 52.227,
      longitude: -1.468,
      location: 'Midlands',
      startDate: 'Aug 2023',
      endDate: null,
      isOngoing: true,
      published: true,
    },
    {
      title: 'Boulby Mine Surface Level Ducting',
      reference: null,
      sector: 'Industrial/Mining',
      client: 'UKRI STFC',
      contractValue: '£150,000',
      designFee: null,
      contract: null,
      description:
        'Designing 2no. duct routes to supply uninterrupted high-speed internet access to the underground laboratory at ICL Boulby polyhalite mine.',
      role: 'Design Engineer',
      latitude: 54.5532,
      longitude: -0.8229,
      location: 'Boulby, North Yorkshire',
      startDate: 'Aug 2023',
      endDate: null,
      isOngoing: true,
      published: true,
    },

    // ─── AUG 2023 ─────────────────────────────────────────────────────────────
    {
      title: 'Boulby Mine Platforms Around Flasks',
      reference: null,
      sector: 'Industrial/Mining',
      client: 'ICL Boulby',
      contractValue: '£250,000',
      designFee: null,
      contract: null,
      description:
        'Design of replacement platforms surrounding product loading flasks, providing lateral support while allowing inspection and adjustment, installed without interrupting product removal from the shaft.',
      role: 'Design Engineer',
      latitude: 54.5535,
      longitude: -0.8235,
      location: 'Boulby, North Yorkshire',
      startDate: 'Aug 2023',
      endDate: null,
      isOngoing: false,
      published: true,
    },
    {
      title: 'Boulby Mine Platforms — Construction Site Support',
      reference: 'Boulby Mine Site Support',
      sector: 'Industrial/Mining',
      client: 'ICL Boulby',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'Following completion of the platform design, I provided site support during construction. I worked directly with the site engineer to resolve problems that arose during the lead-up to installation. I used my knowledge of surveying and CAD software (AutoCAD and Revit) to produce setting-out points that had not been included in the original design submission. I attended the trial erection of the platform to survey the constructed bridge sections and confirm they would install correctly on site. When the existing piers and abutments were surveyed incorrectly by the delivery team, I was able to reassure them and correct the discrepancy by overlaying my trial erection survey data with the proposed model.',
      role: 'Design Engineer (Site Support)',
      latitude: 54.5532,
      longitude: -0.823,
      location: 'Boulby, North Yorkshire',
      startDate: 'Aug 2023',
      endDate: 'Dec 2023',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Kent Street Bridge',
      reference: 'SPC5-4',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: '£430,000',
      designFee: null,
      contract: null,
      description:
        'Post grit blast inspection and repair, sag curve analysis, jack arch tie design, and drainage system design routing water from weep holes to road drainage.',
      role: 'Design Engineer',
      latitude: 53.3795,
      longitude: -1.471,
      location: 'Sheffield',
      startDate: 'Aug 2023',
      endDate: null,
      isOngoing: false,
      published: true,
    },

    // ─── JAN–APR 2023 ────────────────────────────────────────────────────────
    {
      title: 'Eptan Parapet Electrical Risk Assessment — East Coast Mainline',
      reference: 'Eptan Parapet Programme',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'Following multiple police reports of young people climbing on and dangling objects from low parapets, I was asked to assess the electrical risk posed by low parapets on 24 structures along the East Coast Mainline from London to Newcastle. I attended all 24 sites and gathered all required measurements using a laser scanner from public footpaths, without any need to access the railway — significantly improving both safety and efficiency compared to traditional methods. For each structure I undertook the \'taut string line\' assessment in accordance with BS EN 50122-1-2022. This test determines the envelope created by a 3m theoretical string wrapped taut around the base of the parapet, offset by 600mm for 25kV OLE electrical risk. From the results I was able to advise whether each structure required parapet height extensions to be classified as presenting low electrical risk, and produced a schedule of recommended interventions.',
      role: 'Assistant Engineer',
      latitude: 54.0,
      longitude: -1.5,
      location: 'East Coast Mainline — London to Newcastle',
      startDate: 'Jan 2023',
      endDate: 'Apr 2023',
      isOngoing: false,
      published: true,
    },

    // ─── OCT 2022 – AUG 2023 ─────────────────────────────────────────────────
    {
      title: 'York Capacity Improvement Leeman Road',
      reference: 'ECM5-3',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: '£5,000,000',
      designFee: null,
      contract: null,
      description:
        'Design of a single-span billet deck bridge to allow installation of an additional track, relieving the East Coast Mainline of traffic from Harrogate to York.',
      role: 'Assistant Engineer',
      latitude: 53.9595,
      longitude: -1.096,
      location: 'York',
      startDate: 'Oct 2022',
      endDate: 'Aug 2023',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Whatstandwell Station GRP Access Stairway',
      reference: 'AJM1-8B',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: '£115,000',
      designFee: null,
      contract: null,
      description:
        'I was the lead designer for the installation of a GRP access stairway at Whatstandwell Station, allowing a local gardening group to access a disused platform from an existing footbridge. The project required coordination with the Network Rail asset team and the gardening group as stakeholders. I managed the project in a project lead capacity, taking responsibility for programme, cost monitoring and client liaison alongside the design. As part of the project lead role I monitored hours expended against the priced tasks using a cost monitoring spreadsheet, identifying discrepancies between hours used and percentage completion and escalating where required. I also raised a change control when a site visit could not be completed due to a faulty MEWP, securing additional mobilisation costs and updating the programme accordingly.',
      role: 'Assistant Engineer (Lead Designer)',
      latitude: 53.0618,
      longitude: -1.4858,
      location: 'Whatstandwell, Derbyshire',
      startDate: 'Oct 2022',
      endDate: 'Aug 2023',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Railway Cottages Bridge Propping',
      reference: 'FEP-54',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: '£200,000',
      designFee: null,
      contract: null,
      description:
        'Propping system for a single-span steel trough deck bridge — load derivation, 3D frame analysis, steel checks, connection and foundation design. Designed for 10 years until reconstruction.',
      role: 'Design Engineer',
      latitude: 51.8847,
      longitude: -0.4077,
      location: 'Harpenden',
      startDate: 'Oct 2022',
      endDate: 'Aug 2023',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Ford End Road — Masonry Arch Diaphragm Wall',
      reference: 'BBM-39',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: '£63,000',
      designFee: '£8,000',
      contract: 'NR4(MT) – LNE CAM Framework',
      description:
        'Ford End Road BBM/39 is a 19-span masonry arch viaduct overbridge in Bedford, with the first 6 spans over SPC1 and the remaining 13 over BBM. Span 4 had recently had a temporary wall installed to block off the high-mileage face to prevent debris being thrown into the arch. I was remitted to undertake GRIP Stage 4 to design a permanent masonry diaphragm wall replacement. I derived wind and pedestrian loads in accordance with the Eurocodes and factored them using NA to BS EN1990 Table NA.A1.2(A). I checked the wall for overturning and bending in accordance with Eurocode 6 using hand calculations verified with Tekla Tedds design software. The final design comprised 7.3N hollow concrete blocks with H10 vertical reinforcement bars at every other hollow, concrete-filled hollows, bed joint reinforcement at every course, and a 10mm compressible fibreboard expansion joint with SikaFlex Pro-3 sealant. This was my first standalone masonry wall design and the project ran over budget due to time spent pursuing an initially over-conservative approach. I identified the overspend early and escalated to the project lead, which was a key learning experience in design efficiency and cost management.',
      role: 'Assistant Engineer',
      latitude: 52.0406,
      longitude: -0.4627,
      location: 'Bedford',
      startDate: 'Aug 2022',
      endDate: 'Dec 2022',
      isOngoing: false,
      published: true,
    },

    // ─── OCT–DEC 2022 ────────────────────────────────────────────────────────
    {
      title: 'Wellington Street — Cast Iron Beam Fracture Survey',
      reference: 'Wellington Street',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'I attended site at Wellington Street, Gateshead to survey a fractured cast iron beam. On arrival, the MEWP required for the inspection was found to be faulty and the inspection could not be completed safely. I agreed with the site manager that a return visit was required. Back in the office I raised a change control to recover the costs of the aborted visit and the additional mobilisation required for the return, issued it to the design coordinator, and it was accepted. This was an important exercise in commercial management — identifying the cost impact early, preparing a properly evidenced change control, and communicating the programme impact to the relevant parties.',
      role: 'Assistant Engineer',
      latitude: 54.9715,
      longitude: -1.605,
      location: 'Gateshead',
      startDate: 'Oct 2022',
      endDate: 'Dec 2022',
      isOngoing: false,
      published: true,
    },

    // ─── MAR–OCT 2022 ────────────────────────────────────────────────────────
    {
      title: 'Wakefield Westgate — Bridge Strengthening & Repair Design',
      reference: 'DOL2-4',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: '£484,000',
      designFee: '£19,500',
      contract: 'NR4(MT) – LNE CAM Framework',
      description:
        'DOL2/4 Wakefield Westgate is a single-span underbridge on the Wakefield to Leeds line, carrying 3no. electrified operational railway lines and 2no. station platforms over Westgate Road. The bridge achieves only RA6 capacity at the web of the centre main girder (MGI1) at the support, and the parapet girders (LSE1 & LSE2) are substandard due to inadequate compression flange restraint. During optioneering I identified that the scope could be reduced from potential reconstruction to targeted strengthening and repair by undertaking a site inspection and reviewing the structural assessment in detail. Following client acceptance of the optioneering findings, I undertook detailed design for: (1) top flange overplating to MGI1 using the Network Rail Standard Design Detail to achieve RA10+10% capacity at 35mph; (2) stiffener overplating to corroded stiffeners on MGE1 and MGE2 using NR standard details; (3) cleaning and repainting of the corrosion band at the concrete haunch/steel web interface with a 15-year M34 protective system; (4) re-sealing of the concrete haunch-to-web interface with polysulphide sealant. Strengthening of LSE1 and LSE2 platform deck girders to 5kN/m2 capacity was also included in scope.',
      role: 'Trainee Engineer',
      latitude: 53.6815,
      longitude: -1.5009,
      location: 'Wakefield',
      startDate: 'Mar 2022',
      endDate: 'Oct 2022',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Roman Way — Cast Iron Girder Strengthening Options Report',
      reference: 'BOK1-118',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: '£20,000',
      contract: 'NR4(MT) – Anglia CAM Framework',
      description:
        'Overbridge BOK1/118 Roman Way is a single-span overbridge carrying Roman Way over 2no. railway lines with OLE on the Broad Street to Camden Road Junction line. The superstructure comprises 14no. longitudinal cast iron girders with transverse spanning brick jack arches with mass concrete backing, simply supported on brick masonry abutments. The structure had been identified by Network Rail as understrength. I was commissioned to complete a feasibility study covering three options: strengthening to Network Rail liability (7.5T), strengthening to full HA loading (40T), and full reconstruction to HA capacity. I undertook a laser scan, produced capacity calculations to CS454 for each girder, and evaluated eight distinct sub-options including steel overplating, ultra-high modulus carbon fibre plate bonding (Sika structural adhesive), installation of additional beams within the jack arches, and two reconstruction options. I recommended Option 1B — carbon fibre plate strengthening to 7.5T with additional jack arch ties — as it eliminated the need to break out masonry jack arches, avoided drilling of cast iron, achieved a 90% reduction in plate weight compared to steel, and removed the need for girder propping. I organised and chaired an early warning meeting with Network Rail Asset Managers and Route Asset Managers to present and discuss the options prior to report submission. I subsequently presented this project at the Network Rail Health and Safety by Design Developing Engineers Forum in Birmingham.',
      role: 'Trainee Engineer',
      latitude: 51.5474,
      longitude: -0.115,
      location: 'Roman Way, Caledonian Road, London',
      startDate: 'Apr 2022',
      endDate: 'Jul 2022',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Abbey Road — Footbridge Deck Replacement',
      reference: 'Abbey Road-Lincoln Crescent',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: 'NR4(MT) – Anglia CAM Framework',
      description:
        'Abbey Road-Lincoln Crescent is an existing footbridge between Bush Hill Park and Enfield Town stations on the Enfield Town Branch Line, consisting of steel main girders, cast iron stringers, a timber deck, and steel trestles with concrete foundations. The structure was raised during its life to accommodate OLE installation. I was remitted to replace the timber deck and treads with GRP equivalents, repair holed metallic parapets, and treat exposed steelwork at stanchion bases. I paid particular attention to ensuring uniform stair risers and goings throughout each flight in compliance with BS8300:5.9.2 and 5.9.3, which required careful modelling of cast-in stair cleats from the laser scan point cloud and specification of GRP packers to achieve uniform geometry. I worked with a Principal Engineer throughout.',
      role: 'Trainee Engineer',
      latitude: 51.642,
      longitude: -0.0625,
      location: 'Enfield, London',
      startDate: 'Jan 2022',
      endDate: 'Jun 2022',
      isOngoing: false,
      published: true,
    },

    // ─── AUG–DEC 2021 ────────────────────────────────────────────────────────
    {
      title: 'A19 Road Bridge — Weld Fracture Repair',
      reference: 'ECM7/55A',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'A19 Road Bridge is a single-span half-through metallic underbridge with welded plate edge girders, cross beams and trimmer beams compositely connected to a reinforced concrete deck. The remit was GRIP 4 combined F001/2/3 design for repair of a fracture in the welded connection between the main girder inner face and a cross girder. I completed design calculations taking a conservative approach of providing sufficient bolt strength to fully replace the weld capacity, given that overplating would prevent future inspection of the weld. The calculation process involved determining the full shear resistance of the intact weld, sizing the required bolt arrangement, and selecting appropriate M24 HSFG bolts from the steelwork blue book. I additionally proposed that the weld fracture be drilled at its tip to arrest further propagation, and produced a full set of design drawings and a Designers Risk Assessment.',
      role: 'Trainee Engineer',
      latitude: 54.5781,
      longitude: -1.3184,
      location: 'Stockton-on-Tees',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Harringay Portland Gardens — Track Access Point',
      reference: null,
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'Site access point design including laser scanning, trial pit logging, access path and steps design for safe track-level access.',
      role: 'Trainee Engineer',
      latitude: 51.5822,
      longitude: -0.1007,
      location: 'Harringay, London',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Corsica Street — Bridge Propping Packing',
      reference: 'BOK1-129',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: 'NR4(MT) – Anglia CAM Framework',
      description:
        'Corsica Street BOK1-129 is a redundant span of a bridge comprising riveted steel external girders, cast iron internal girders, and masonry jack arches. The bridge was propped with trestle supports, but a gap between the girder soffits and the propping beam had been filled with soft rubber/foam packing, meaning none of the bridge\'s self-weight was being transferred into the propping as intended. I attended site via ladder access during a possession from Highbury and Islington station and laser scanned the underside to produce an accurate Revit/AutoCAD model. I evaluated three options — grout bags, proprietary wedge systems, and steel packing plates — and designed a steel packing plate solution following discussion with the contractor on site. The solution properly fills the gap between the propping and the bottom flanges of the girders, restoring the propping to its intended function.',
      role: 'Trainee Engineer',
      latitude: 51.5441,
      longitude: -0.1041,
      location: 'Corsica Street, Highbury, London',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Caledonian Road — Parapet Stabilisation Optioneering',
      reference: 'Caledonian Road Parapet',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: 'NR4(MT) – Anglia CAM Framework',
      description:
        'Optioneering report for the stabilisation of an unstable masonry parapet on a viaduct structure between Caledonian Road & Barnsbury and Highbury & Islington stations. The parapet showed significant outward movement and required an engineered solution. I developed three options: Option 1 — demolish and rebuild in-situ masonry with dowelled L-shaped base to prevent overturning; Option 2 — install a reinforced concrete backing to the existing parapet, again L-shaped and dowelled; Option 3 — demolish and replace with precast L-shaped parapet sections, crane-installed in manageable lifts. Each option was assessed for buildability, programme impact, and structural performance. The precast option offered advantages in speed of installation and reduced formwork requirements.',
      role: 'Trainee Engineer',
      latitude: 51.544,
      longitude: -0.1145,
      location: 'Caledonian Road, London',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Mick Gladden — Ballast Retention Wall Replacement',
      reference: 'Mick Gladden BRW',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'I attended site to undertake a laser scan, dimensional survey, defect inspection, services survey, and signage check of the ballast retention wall. Major defects identified included a large root causing a 30–45mm open fracture through the full height of the wall continuing as a hairline fracture into the abutment, a stepped-out section of masonry wall parallel to track, and an additional fracture near the pier. A previous repair appeared to have been carried out incorrectly using plain grout fill rather than a proper stitch-and-grout method. I presented site findings and recommended partial rebuild with root removal. Following client acceptance, I progressed to detailed design, determining that temporary ballast retention would be required during reconstruction to protect the track support zone. I evaluated BaFix ballast retention, steel plates fixed to the pier, and concrete blocks before selecting the preferred solution and completing a full set of design drawings.',
      role: 'Trainee Engineer',
      latitude: 53.69,
      longitude: -1.47,
      location: 'Yorkshire',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Glengalls Bridge — Pedestrian Gate Feasibility Laser Scan',
      reference: 'Glengalls Bridge',
      sector: 'Environment',
      client: 'Network Rail / Canal & River Trust',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'I attended Glengalls Bridge, Canary Wharf to complete laser scanning of the moveable bridge structure. The scan needed to be completed in both the open and closed bridge positions to allow an accurate Revit model to be produced in both configurations. The purpose of the model was to assess the viability of installing pedestrian gates to prevent access to the bridge during opening and closing operations — a public safety requirement. Major hazards managed on site included working near waterways, interface with members of the public, and working near moving structures. I managed these risks by maintaining safe distances from exposed waterway edges, positioning the scanner to allow free pedestrian movement, and waiting for full cessation of bridge movement before repositioning equipment.',
      role: 'Trainee Engineer',
      latitude: 51.5011,
      longitude: -0.0157,
      location: 'Canary Wharf, London',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Brentwood Station — Footbridge Abutment Masonry Repairs',
      reference: 'Brentwood Station',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'I attended site to undertake a masonry defect inspection to the footbridge abutment at Brentwood Station. The purpose of the visit was to determine whether standard repair details could be applied or whether a detailed structural design was required. Defects identified included fractures to the abutment corners likely caused by root growth, areas of new brickwork that had stepped out and were drummy on inspection, multiple masonry fractures including a vertical fracture to the full abutment section, and a missing brick from the string course. Following discussion with the Senior Engineer I concluded that a mix of standard masonry repair details and a localised propping scheme was required depending on the extent of movement in each defect area.',
      role: 'Trainee Engineer',
      latitude: 51.6154,
      longitude: 0.3046,
      location: 'Brentwood, Essex',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Newmarket Station — Concrete Outrigger Foundation Repair',
      reference: 'Newmarket Station',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'The remit required a review of defects to the concrete outrigger foundation at Newmarket Station. I reviewed available information including inspection photographs prior to attending site. On site I assessed the extent of defects, confirmed no new defects had formed, and confirmed that existing defects had not worsened and remained minor in nature. I managed site risks including working in a live rail environment, slips trips and falls, and proximity to electrified metal by attending the COSS briefing, confirming the possession was in place before track access, and wearing full appropriate PPE. I concluded that the defects could be addressed using standard concrete repair details without detailed design input.',
      role: 'Trainee Engineer',
      latitude: 52.2395,
      longitude: 0.4068,
      location: 'Newmarket, Suffolk',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'The Wood — Steelwork Overplating & Repainting',
      reference: 'The Wood Footbridge',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'An existing steel footbridge with concrete deck over 2no. non-electrified lines. The remit was to inspect damage to the main girders above the trestle supports and abutments and provide repair details. I attended site with a roped access team, undertook a detailed inspection of the girders above the abutments, completed a general dimensional survey and briefed the roped access team on the specific information required for the design. I paid careful attention to the gap between the bottom flange and an existing aqueduct, as there were concerns about the clearance available for plate installation. Having confirmed sufficient clearance, I proposed web overplating above the trestle supports using HSFG bolted connections, rejecting welding due to limited access height, fire risk, and the eccentricity that a single-face plate weld would introduce. Girder soffits above abutments were scoped for repainting only as no structural deficiency was found in these areas.',
      role: 'Trainee Engineer',
      latitude: 51.578,
      longitude: -0.029,
      location: 'Walthamstow, London',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Church Footbridge — Bridge Deck Replacement Drawing Amendments',
      reference: 'Church Footbridge',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'My role was to review and incorporate client comments on the design drawings for a bridge deck replacement scheme. The principal comment required the inclusion of corduroy tactile pavers at stair heads and tails, which had been omitted from the original design due to the rural setting of the bridge. I reviewed the Network Rail Footbridge Standard Detail, confirmed the requirement for tactile strips in non-station footbridges, accepted the comment, and revised the drawings accordingly. Tactile paving was specified at the top and bottom of each stair flight in line with the standard, contributing to social sustainability and accessibility in line with BS8300.',
      role: 'Trainee Engineer',
      latitude: 51.62,
      longitude: -0.1,
      location: 'Hertfordshire',
      startDate: 'Aug 2021',
      endDate: 'Dec 2021',
      isOngoing: false,
      published: true,
    },

    // ─── MAY–JUL 2021 ────────────────────────────────────────────────────────
    {
      title: 'Green Drive — Jack Arch Tie Installation',
      reference: 'MAC3/189',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: 'NR4(MT) – Anglia CAM Framework',
      description:
        'Structure MAC3/189 is a single-span overbridge located between Worksop and Birmingham Moor Street stations. The deck comprises 5no. cast iron girders with masonry jack arches spanning between them, carried on masonry abutments and wing walls over 2no. operational tracks. The existing tie bars were hooked onto the girders and failed Current Information Sheet 22 (CIS22). I designed a new jack arch tie arrangement using NR/CIV/SD/1800 and NR/CIV/SD/1801, modifying the standard end bay clamping arrangement to maintain sufficient clamping area on the bottom flange of the outer girder. Gauging concerns were identified as the existing structure did not meet NR-L3-TRK-mod7 requirements; I produced an additional option to reduce headroom impact, which was reviewed and discounted following discussion with the Senior Engineer as it was unnecessary.',
      role: 'Trainee Engineer (Designer & CAD Technician)',
      latitude: 53.1875,
      longitude: -1.12,
      location: 'Between Worksop and Birmingham Moor Street',
      startDate: 'May 2021',
      endDate: 'Jul 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Site Access Points — Lower Dunton Road, Chestnuts Road, Clarence Road & Private Road',
      reference: 'Anglia Access Points',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: 'NR4(MT) – Anglia CAM Framework',
      description:
        'Four site access points in the Anglia region requiring design of access stairs, car park surfacing and Armco barrier installation. I acted as both design engineer and CAD technician on all four schemes. Works included option preparation and selection accounting for geometric constraints (existing structures, trees, services, ground inclination) and environmental constraints (nesting birds, invasive species). The preferred stair solution across all sites was the Stanton Bonna precast concrete stair due to ease of installation and team familiarity. I designed a retaining wall for one site, sizing the embedded depth of sheet piles using HA66/95 Appendix C. Ecological survey recommendations and seasonal working restrictions were communicated via the Designers Risk Assessment and highlighted on drawings.',
      role: 'Trainee Engineer (Designer & CAD Technician)',
      latitude: 51.55,
      longitude: 0.38,
      location: 'Anglia Region, Essex',
      startDate: 'May 2021',
      endDate: 'Jul 2021',
      isOngoing: false,
      published: true,
    },
    {
      title: 'Cannon Street — Track Access Lift Feasibility',
      reference: 'Cannon Street Access',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: null,
      description:
        'Cannon Street access point is an existing track access stairway near Shadwell Station, London, running over a multi-span viaduct. I was remitted to produce a feasibility options report for the installation of a materials access lift. I attended site to undertake a condition survey, drainage survey, and ground investigation including 2no. trial pits to understand ground conditions and existing foundation details. I laser scanned the structure to produce an accurate model. The options report covered lift positioning, local parapet removal, foundation installation, power supply from an adjacent DNO cabinet, and drainage rerouting. The lift was positioned at midspan of the arch to avoid clashes with arch access doors and an existing redundant OLE mast. I organised a meeting with Alimak (Access Lift Supplier) to clarify foundation requirements and potential technical issues.',
      role: 'Trainee Engineer',
      latitude: 51.5107,
      longitude: -0.0597,
      location: 'Cannon Street / Shadwell, London',
      startDate: 'May 2021',
      endDate: 'Jul 2021',
      isOngoing: false,
      published: true,
    },

    // ─── MAR 2019 – JUL 2021 ─────────────────────────────────────────────────
    {
      title: 'Jack Arch Tie Programme — Multiple Schemes',
      reference: 'CC0248 / CC0255 / CC0261 / CC0324 / CC0354 / CC0355 / CC0421',
      sector: 'Rail',
      client: 'Network Rail',
      contractValue: null,
      designFee: null,
      contract: 'NR4(MT) – Multiple CAM Frameworks',
      description:
        'From 2019 to 2021 I designed and produced drawings for jack arch tie installations on seven schemes across the Network Rail estate, all in accordance with CIS22 and using tie details from NR/CIV/SD/2800 and 2801. Each scheme required assessment of the number and spacing of ties required to achieve 40-tonne capacity in compliance with the CIS22 empirical method. Key schemes included: Rumbush Lane (TSB-29) — non-standard soffit and clamping plates required where the clamping arrangement bore onto a doubler plate rather than directly onto the bottom flange; Vicarage Road (SKN-138) — resin anchors through the bottom flange were used instead of the standard clamping arrangement due to limited construction clearance adjacent to a masonry arch span; Ragnall Road (CLN3-90) — identified that replacing a single corroded tie would not achieve CIS22 compliance, resulting in full outer bay tie installation; Goods Yard Approach (LEC1-73) — non-standard soffit and clamping plates designed to avoid clashes with existing rivets, with headroom check for 25m vehicle; Coote Lane and Chapel Street (FHR1-2 / FHR4-21) — unique tightener-based clamping arrangement developed where the existing service bay plate prevented the standard detail; Cathiron Bridge (LEC2-9B) — longitudinally spanning jack arches with masonry repairs to jack arches and wing walls included as part of the scheme.',
      role: 'Trainee Engineer (Designer & CAD Technician)',
      latitude: 52.4,
      longitude: -1.5,
      location: 'Various — Midlands & London',
      startDate: 'Mar 2019',
      endDate: 'Jul 2021',
      isOngoing: false,
      published: true,
    },
  ]

  for (const project of projects) {
    await prisma.project.create({ data: project })
  }

  console.log(`Seeded ${projects.length} projects`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
